# Generated by Django 4.2.1 on 2023-06-01 01:08

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcionAmplia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcionBrebe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='dirigido_a_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='dirigido_a_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='dirigido_a_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='dirigido_a_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='curso',
            name='modulo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modulo2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modulo3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modulo4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modulo5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modulo6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modulo7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.AddField(
            model_name='mentore',
            name='descripcion_amplia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentore',
            name='descripcion_breve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentore',
            name='imgconsultor',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='mentore',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
