# Generated by Django 4.2.1 on 2023-05-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_curso_descripciondentrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='descripcionDentrp',
            new_name='descripcionDentro',
        ),
    ]
