# Generated by Django 4.2.1 on 2023-06-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_curso_descripcionamplia_curso_descripcionbrebe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='dirigido_a_2',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='dirigido_a_3',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='dirigido_a_4',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='modulo2',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='modulo3',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='modulo4',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='modulo5',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='modulo6',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='modulo7',
        ),
    ]
