# Generated by Django 4.2.1 on 2023-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_curso_aprenderas2'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aprenderas3',
            field=models.TextField(null=True),
        ),
    ]
