# Generated by Django 4.2.1 on 2023-05-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_curso_aprenderas4'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='urlVideo',
            field=models.TextField(null=True),
        ),
    ]
