# Generated by Django 4.2.1 on 2023-05-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_curso_urlvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='urlVideo',
            new_name='video',
        ),
    ]
