# Generated by Django 4.2.1 on 2023-05-29 05:00

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_rename_urlvideo_curso_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
